
= Considerações finais

Esta tese analisou o processo da teoria da atenção conjunta com o objetivo de analisar a Atenção Conjunta Digital (ACD) entre crianças e um livro interativo digital, por meio da mediação de um narrador virtual. Nossa hipótese foi confirmada, demonstrando que a Atenção Conjunta Digital ocorreu através do funcionamento linguístico multimodal. Observamos que a interação triádica, envolvendo a criança, o livro interativo digital e os comandos realizados pelos personagens ou pelo narrador virtual, promoveu um maior engajamento e atenção das crianças na história interativa.

A efetivação da Atenção Conjunta Digital pode ser comprovada graças às pistas multimodais e os recursos linguísticos que contribuíram para o registro do engajamento das crianças leitoras dentro de contextos digitais e interativos. Os recursos multimodais presentes no livro desempenharam um papel crucial na interação. Num primeiro momento, a multimodalidade imagética foi a responsável pelo processo de interação entre os leitores e livro interativo digital, como cores, símbolos e sons que estimularam o engajamento dos participantes, mas como íamos saber se essas crianças estavam em atenção conjunta? Foi aí que, em um segundo momento, os recursos presentes na dinâmica multimodal da linguagem, na qual os gestos produzidos pelas crianças foram cruciais para perceber que elas estavam em Atenção Conjunta Digital com o Livro Interativo Digital.

Realizamos uma revisão abrangente do estado da arte dos estudos sobre Atenção Conjunta (AC), abordando tanto pesquisas nacionais quanto internacionais. Destacamos inicialmente a conexão entre AC e estudos de linguística, reunindo estudos recentes e significativos para oferecer uma visão atualizada e abrangente da temática. No contexto nacional, foram utilizadas três ferramentas de busca para levantar pesquisas no período de 2013 a 2023, priorizando os trabalhos em linguística. As principais fontes consultadas foram a Biblioteca Digital Brasileira de Teses e Dissertações (BDTD) e o Catálogo de Teses e Dissertações da CAPES. Observamos um crescimento no número de trabalhos sobre AC, especialmente na região Nordeste, com destaque para a Universidade Federal da Paraíba (UFPB). No entanto, a nossa pesquisa mostrou que o tema ainda não é tão explorado quanto em outras áreas, como psicologia e educação.  

A análise internacional foi realizada em bases de dados como a Scopus e Web of Science. Encontramos nessas bases de dados uma predominância de estudos sobre AC na psicologia. Buscamos registrar os trabalhos voltados para o campo da linguística, pois a presença de trabalhos sobre AC na linguística é menos expressiva, representando apenas uma pequena parcela do total de pesquisas. Além disso, a pesquisa revelou uma concentração significativa de trabalhos sobre AC em contextos relacionados ao autismo, especialmente na psicologia.  

Uma abordagem cartográfica foi adotada para analisar a distribuição geográfica e temática das pesquisas sobre AC no Brasil. Destacou-se a Paraíba como o Estado com maior produção de trabalhos sobre AC, seguido de outras regiões do país. A Universidade Federal da Paraíba se destaca como a instituição líder na produção de pesquisas sobre AC. A análise dos orientadores e das temáticas de pesquisa revelam padrões consistentes com os dados gerais, destacando a importância de pesquisadores e instituições específicas na produção acadêmica sobre AC. 

O capítulo II teve como objetivo apresentar uma revisão abrangente da teoria da atenção conjunta (AC), desde sua origem até as pesquisas mais recentes. A AC foi definida como a capacidade de coordenar a atenção com outro indivíduo em um objeto ou evento de interesse mútuo. A revisão da literatura abordou a origem da teoria da AC nos estudos de Jerome Bruner e Michael Tomasello. O processo da AC foi detalhado, incluindo seus diferentes tipos e os três estágios principais de desenvolvimento propostos por Tomasello: atenção de verificação, atenção de acompanhamento e atenção direta.  

A seção sobre a ACV apresentou um panorama dos estudos de Costa Filho (2011, 2016), pelas nossas pesquisas podemos perceber que essa nova especificidade da AC, pode se manifestar em interações mediadas entre os interlocutores face a face no plano físico como também por tecnologias digitais no meio digital. Essa nova forma de interação abriu um leque de possibilidades para a pesquisa e a prática em diversas áreas, como educação, psicologia e comunicação. Além de corroborar para que essa tese fosse pensada e desenvolvida. A partir dos estudos pioneiros de Costa Filho (2011; 2016; 2017; 2018; 2021), foram identificadas as principais características da ACV realizada pelo autor no meio digital. Estas incluem interação mediada por tecnologias digitais, interlocutores em diferentes espaços, compartilhamento de atenção e foco, além do uso de atos de referência linguística. Essas características permitiram construir uma base teórica para ampara as nossas pesquisas sobre Atenção Conjunta Digital.

Esta tese também discutiu de forma breve mais muito objetiva sobre a oposição entre o virtual e o real, esta dicotomia foi apresentada por Pierre Lévy em sua obra seminal "O Que é o Virtual?" (2011), que nos conduz a uma compreensão mais profunda das inter-relações entre esses dois domínios aparentemente distintos. Lévy desafia a noção de que o virtual está restrito ao âmbito tecnológico, enfatizando que ela é uma dimensão essencial da realidade contemporânea, permeando todos os aspectos da vida moderna e não só no meio tecnológico. Essa compreensão ressalta a presença do virtual em nossa existência cotidiana.  

Ao explorar o conceito de virtualidade, Lévy destaca sua presença no corpo, no texto, na economia e em diversas outras esferas da experiência humana. Ele argumenta que o virtual não é uma mera potencialidade, mas uma força que influencia ativamente a realidade, moldando nossas interações, comunicações e percepções.  

A compreensão de que o virtual está presente em todas as coisas, independentemente do contexto tecnológico, nos leva a repensar a natureza da Atenção Conjunta e suas especificidades. Enquanto tradicionalmente associamos a AC à interação entre indivíduos em um espaço físico compartilhado, a emergência da Atenção Conjunta Virtual e da Atenção Conjunta Digital nos desafiam a expandir essa concepção para outros espaços e outros tempos. 

A ACV e a Atenção Conjunta Digital não se limitam à ausência física dos participantes; elas englobam uma gama de interações mediadas por dispositivos digitais, integrando o real e o virtual de maneiras complexas.

Ao considerar a Atenção Conjunta Digital, é fundamental reconhecer que o virtual não é uma realidade separada, mas sim uma dimensão intrínseca à nossa experiência cotidiana. A Atenção Conjunta Digital nos leva a questionar as fronteiras entre o físico e o digital, desafiando-nos a repensar o significado da interação e da comunicação em um mundo cada vez mais digitalizado.  

Portanto, ao explorar a complexidade da Atenção Conjunta Digital e suas ramificações para a teoria e prática da atenção conjunta, é essencial adotar uma abordagem holística que leve em consideração tanto o contexto tecnológico quanto as dinâmicas sociais e culturais que moldam nossas interações. Somente assim poderemos compreender plenamente o impacto da Atenção Conjunta Digital na forma como nos comunicamos, colaboramos e interagimos com o mundo ao nosso redor.  

Nossa pesquisa se revelou inspiradora sobre o papel transformador da Atenção Conjunta Digital (ACD) na leitura, especialmente no contexto dos livros digitais. Ao longo do estudo, foi possível compreender como a interação pode gerar uma experiência de aprendizado única e significativa entre a criança, o interlocutor virtual e o conteúdo digital. 

A ACD emerge como um farol que guia a leitura para novos horizontes, convidando as crianças a uma jornada interativa e engajadora através do universo dos livros digitais. Essa interatividade não apenas desperta o interesse da criança, mas também promove o desenvolvimento de uma série de habilidades essenciais, incluindo linguagem, pensamento crítico e habilidades socioemocionais.

Ao reconhecer o potencial da ACD, somos instigados a agir e a refletir sobre o seu impacto no desenvolvimento infantil e pensar na educação é uma possibilidade pois como já afirmamos anteriormente esta tese não foi pensada na área educacional, mas de uma forma indireta perpassa pela na educação por se tratar de crianças que estão em uma fase de alfabetização. Por isso é importante que educadores, pais, desenvolvedores de aplicativos (programadores) e toda a comunidade possam ser convidados a se unirem em um esforço conjunto para promover a criação e o uso eficaz de livros digitais que incorporem os princípios da ACD.  

Essa jornada não se encerra aqui. Ao contrário, esta pesquisa representa apenas o início de uma jornada contínua e empolgante rumo a um futuro no qual a leitura seja uma experiência enriquecedora e transformadora para todas as crianças. Convidamos todos a se juntarem a nós nessa jornada, explorando novas possibilidades, pesquisando novas abordagens e inovando para criar um mundo onde o poder da ACD seja plenamente realizado. Juntos, podemos construir um legado duradouro para as gerações futuras, onde a leitura seja verdadeiramente um farol que ilumina o caminho para o conhecimento, a criatividade e a realização humana. 

Exploramos o diálogo inspirador entre a ACD e a Teoria Enunciativa de Benveniste. Essa convergência teórica nos permitiu aprofundar a compreensão do processo de leitura mediado por tecnologias digitais, revelando as nuances da interação entre o sujeito (eu benvenistiano), o interlocutor virtual (o tu benvenistiano) e o livro interativo digital (o ele).  

As convergências entre a ACD e a Teoria Enunciativa se manifestam em diversos aspectos como os processos da triangularidade que envolve a ACD e a enunciação benvenistiana que operam em uma estrutura triangular, envolvendo o sujeito/eu, o interlocutor/tu e o objeto/ele, (livro interativo digital). Ambas as perspectivas reconhecem a importância da intersubjetividade na construção de significados durante a leitura e ou a interlocução. Dentro dos estudos benvenistianos, a dêixis se torna crucial na ACD, pois o sujeito precisa se posicionar em relação ao interlocutor virtual e ao conteúdo do livro interativo digital. Outro ponto importante discutido nesta tese foi como a ACD pode proporcionar novas formas de construção do discurso, com a interação entre o sujeito, o interlocutor virtual e o livro interativo digital.  

O diálogo entre a ACD e a Teoria Enunciativa é um processo contínuo e acreditamos que deve ser aprofundado e enriquecido por novas pesquisas e estudos. Essa convergência teórica também abre um leque de possibilidades para a investigação e o desenvolvimento de práticas inovadoras de ensino e aprendizagem, com o objetivo de promover o desenvolvimento integral da criança através da leitura.  

A jornada da leitura mediada por tecnologias digitais está apenas começando. Acreditamos que a ACD, em diálogo com a Teoria Enunciativa e outras perspectivas teóricas, continuará a contribuir para a construção de um futuro em que a leitura seja um farol que ilumina o caminho para o conhecimento, a criatividade e a realização humana.  

Ao longo desta pesquisa, exploramos a complexa interação multimodal entre linguagem gestual e a enunciação, destacando sua importância na comunicação humana e no desenvolvimento de tecnologias interativas. A linguagem gestual, desde os primórdios da evolução humana, tem desempenhado um papel fundamental na expressão de pensamentos e significados, tanto de forma independente quanto em conjunto com a fala.  

A linguagem gestual e a multimodalidade desempenharam um papel importante na coordenação e na partilha de atenção entre os participantes da interação. Através de gestos, expressões faciais e outros sinais não verbais, os indivíduos podem direcionar e manter a atenção conjunta em objetos, eventos ou ideias, facilitando a comunicação eficaz e a compreensão mútua. 

Além disso, exploramos o papel das expressões faciais na comunicação humana, destacando a universalidade de certas expressões e seu impacto no reconhecimento e interpretação de emoções. A análise das emoções e expressões faciais revelou percepções importantes sobre o funcionamento da comunicação não verbal e sua influência na interação social e no desenvolvimento humano.  

Avançando para o contexto contemporâneo, investigamos o papel das tecnologias, especialmente dos dispositivos touchscreen, na comunicação multimodal. A integração de diferentes modalidades sensoriais, como toque, visão e som, tem ampliado as possibilidades de interação homem-máquina, proporcionando experiências mais imersivas e acessíveis.  

A compreensão desses conceitos e fenômenos tem implicações significativas em diversas áreas, incluindo linguística, psicologia, tecnologias da informação e comunicação. Ao reconhecer a importância da linguagem gestual, da multimodalidade e da atenção conjunta na comunicação humana, podemos desenvolver melhores estratégias de ensino (que não é nosso foco nessa pesquisa) mas acreditamos ser importante, criar tecnologias  mais inclusivas e promover uma maior compreensão intercultural.  

Por fim, esta tese destaca a necessidade contínua de investigação e desenvolvimento neste campo, visando aprimorar nossa compreensão da linguagem gestual, da multimodalidade, da atenção conjunta e de sua relação com a enunciação. Através de um diálogo interdisciplinar e da colaboração entre diferentes áreas de estudo, podemos avançar no entendimento da complexidade da comunicação humana e explorar todo o seu potencial em diversas esferas da vida humana.  

Relacionamos, no capítulo V, quais foram os caminhos metodológicos da pesquisa e descrevemos o método utilizado nesta tese que investigou o processo de Atenção Conjunta Digital (ACD) de três crianças processo de alfabetização mediado por narrativas de um livro interativo digital.  

A pesquisa também apresentou informações sobre os participantes da pesquisa, os critérios para a seleção do livro interativo "O mistério do Sr. Gratus", e detalhes sobre a coleta de dados, incluindo o tempo de gravação das leituras realizadas pelas crianças e o processo de edição dos vídeos. 

O capítulo VI tratou da análise dos dados coletados desta tese, especialmente nas interações promovidas dos três participantes durante a leitura de um livro interativo digital. Essa seção descreveu como a ACD se manifesta nas interações, principalmente através de recursos multimodais presentes no livro. Outro ponto discutido neste capítulo foi constatar a relevância e o potencial da Atenção Conjunta Digital (ACD) como uma ferramenta promissora para aprimorar a interação e o engajamento dos leitores, especialmente crianças, em ambientes digitais. A análise dos dados coletados a pesquisa revelou indícios claros de ACD, destacando a presença de recursos multimodais nos livros interativos digitais, os quais facilitam a percepção da imersão dos participantes na história. 

A Atenção Conjunta Digital, descrita como um processo triádico envolvendo usuário/leitor, narrador virtual e elementos digitais, demonstrou ser uma abordagem eficaz para promover interações mais dinâmicas e envolventes. Através de recursos como cliques e movimentos de arrastar na tela para ativar objetos na história além das decisões tomadas pelo leitor que modifica a narrativa, tornando-os agentes ativos na construção do enredo, contribuindo para uma experiência de leitura mais personalizada e participativa.  

Além disso, a análise das interações evidenciou a importância da coordenação de olhares, da utilização dos gestos e da produção vocal dos participantes como componentes-chave da ACD. Estas manifestações demonstram não apenas o envolvimento dos participantes, mas também a capacidade dos recursos digitais em promover uma comunicação eficaz e colaborativa.  

Os resultados desta pesquisa destacaram não apenas o potencial dos livros interativos digitais como ferramentas educacionais e de entretenimento, mas também a importância de se compreender e explorar os mecanismos subjacentes à interação digital.   

Portanto, concluo que a Atenção Conjunta Digital representa uma área de estudo promissora, com amplas implicações para o desenvolvimento de recursos educacionais e culturais que visam promover uma maior participação e envolvimento dos usuários em ambientes digitais.   

Por fim é necessário destacar que ao longo desta pesquisa, desvendamos a complexa e fascinante teia que entrelaça a Atenção Conjunta Digital (ACD) e os livros interativos digitais. Através de uma análise aprofundada, fundamentada em pesquisas e estudos relevantes, evidenciamos o potencial transformador da ACD para a leitura, especialmente no que tange ao desenvolvimento integral da criança.  

Mostramos que a ACD se configura como um paradigma inovador na leitura, transcendendo a mera passividade e convidando a criança a um mergulho interativo e engajador no universo dos livros interativos digitais. A interação triádica entre a criança, o interlocutor virtual e o livro interativo digital se torna uma bússola que guia a jornada de leitura para novos horizontes, onde a aprendizagem se torna uma aventura empolgante e significativa.  

Ao integrar os princípios da interatividade e da cooperação, a Atenção Conjunta Digital 
(ACD) promove uma sinfonia de benefícios para a aprendizagem da criança, nutrindo o desenvolvimento de habilidades essenciais para o seu futuro. A nossa pesquisa pode demonstrar que a ACD oferece uma abordagem inovadora e promissora para promover a aprendizagem por meio da leitura digital interativa. Os resultados evidenciam que os livros digitais baseados em ACD podem se destacar como ferramentas poderosas para o desenvolvimento integral da criança, preparando-a para os desafios e oportunidades do amanhã.  

Diante do panorama promissor delineado por esta pesquisa e mesmo não sendo nosso objetivo principal, mas sim transversal, é imperativo convidar (repito) educadores, pais, profissionais de TI e toda a comunidade a se unirem em um esforço conjunto para aproveitar ao máximo o potencial da ACD na educação infantil. Para tanto, é necessário promover a criação de livros digitais que incorporem os princípios da ACD, investindo na produção de materiais interativos, lúdicos e de alta qualidade que engajem a criança e a incentivem a explorar o mundo da leitura de forma autônoma e prazerosa.  

Além disso, é fundamental capacitar educadores para o uso eficaz da ACD em sala de aula. Através de formações continuadas e materiais de apoio, podemos empoderar os educadores para que utilizem a ACD como uma ferramenta pedagógica inovadora, capaz de transformar a experiência de leitura em um processo de aprendizagem dinâmico e enriquecedor. É necessário que as famílias compreendam os benefícios da ACD e incentivem seu uso no ambiente familiar, criando um espaço propício para o desenvolvimento da leitura e da aprendizagem das crianças. 

Ao abraçarmos a ACD como um paradigma transformador na leitura, estamos construindo um legado para as gerações futuras. Um legado de aprendizagem ativa, engajadora e significativa, onde a tecnologias, a psicologia, a linguística e a pedagogia se unem para criar experiências de leitura que nutrem a mente, o coração e a alma da criança. Esta pesquisa representa apenas o início de uma jornada empolgante. Acreditamos que a ACD tem um potencial inesgotável para revolucionar a leitura e o aprendizado das crianças. Convidamos todos a se unirem a nós nesta jornada, explorando, pesquisando e inovando para construir um futuro em que a leitura seja um farol que ilumina o caminho para o 
conhecimento, a criatividade e a realização humana.  

#pagebreak()