= INTRODUÇÃO

A ciência é viva, mutável e inacabada. Um fluído ou um espectro que toma determinadas
formas de acordo com o momento científico das hipóteses (heurísticas) que estão atuando sobre elas. As teses construídas ao longo do tempo fortalecem as teorias e provocam interlocuções com outras de maior afinidade ou de objetos de estudos semelhantes, contribuindo para a expansão das ciências. Em determinados momentos, o que difere é apenas a perspectiva do pesquisador, assim como disse Saussure “o ponto de vista é que define o objeto” @saussure2012[p. 39] no início do século XX.

Foi assim, através da interlocução científica, que nasceram as pesquisas sobre os estudos da Atenção Conjunta, doravante AC, um construto teórico do campo das Ciências da Linguagem, que advém da Psicologia do Desenvolvimento em meados de 1970, a partir dos trabalhos de Bruner (#cite(<bruner1975>, form: "year"), #cite(<bruner1983>, form: "year")), dos quais foram feitos vários estudos da aquisição da linguagem humana. 


A teoria da Atenção Conjunta (AC) pode ser observada em diversas áreas do
conhecimento, a exemplo da Psicologia Cognitiva, Antropologia, Sociologia, Linguística e Primatologia. Segundo Miguens (#cite(<miguens2015>, form: "year")), a AC é uma teoria na qual a ciência cognitiva se debruça. Trata dos estudos que envolvem a mente e a interação entre sujeitos, com o interesse voltado para o desenvolvimento dentro das ciências cognitivas.

Fonte (#cite(<fonte2011>, form: "year")) que foi a partir de meados do século XX, mais precisamente em 1970, que surgiram os primeiros estudos mundiais sobre a Atenção Conjunta, acompanhando o aparecimento de uma “revolução cognitiva” da linguagem que investigou a comunicação humana e sua interação nas ciências @miller_2003. Desta forma, com menos de meio século de existência, os estudos da AC caracterizam-se como um campo novo quando comparado a outras investigações das ciências da linguagem.

No Brasil, os trabalhos em Atenção Conjunta ganharam grande visibilidade na
Linguística no início do século XXI com Leite (#cite(<leite2008>, form: "year"))  ; Vieira (#cite(<vieira2009>, form: "year")) além dos estudos de aquisição de linguagem de Cavalcante (#cite(<cavalcante2009>, form: "year")) e colaboradores @costa_filho2011, @melo2015, quando começaram a observar, sobretudo, a relação linguageira estabelecida entre os bebês e suas mães em aquisição de linguagem. Em ambiente de creche, encontramos a pesquisa de Melo (2015) com a interação entre alunos e professoras. As pesquisas se expandiram para trabalhos com sujeitos atípicos, a exemplo de crianças cegas @fonte2011, de crianças autistas @fonte_cavalcante_2018 e com Síndrome de Down a partir das pesquisas de Ávila Nóbrega (#cite(<avila_nobrega2017>, form: "year"), #cite(<avila_nobrega2018>, form: "year")), e Lima (#cite(<lima2020>, form: "year")). Além dessas pesquisas, é importante ressaltar os trabalhos de Costa Filho (#cite(<costa_filho2011>, form: "year"); #cite(<costa_filho2016>, form: "year"); #cite(<costa_filho2017>, form: "year");#cite(<costa_filho-marianne2018>, form: "year"); #cite(<costa_filho2021>, form: "year")) sobre Atenção Conjunta em meio virtual.

Embora as pesquisas sobre atenção conjunta em contextos virtuais tenham avançado, a interação específica mediada por livros interativos digitais ainda carece de investigação profunda sob a ótica da aquisição da linguagem. Diante dessa lacuna, a presente tese investiga a emergência da Atenção Conjunta Digital, explorando a tríade estabelecida entre a criança, o adulto e o livro literário em suporte tecnológico. Parte-se da premissa de que esse objeto digital não é apenas um meio passivo, mas um agente mediador cujos recursos multimodais e design interativo podem promover e sustentar o engajamento triádico. Nesse sentido, o problema central desta investigação consiste em verificar de que maneira os elementos semióticos e os recursos de interatividade do livro digital atuam como facilitadores da focalização compartilhada e do desenvolvimento linguageiro nesse novo nicho tecnológico.

Os estudos sobre Atenção Conjunta são relativamente novos, como já citado anteriormente. Em nossas pesquisas sobre os estudos da AC relacionadas ao uso das tecnologias, encontramos, no Brasil, apenas as pesquisas sobre a Atenção Conjunta Virtual que foram iniciadas por Costa Filho (2011). Sua dissertação já tratava sobre a Atenção Conjunta Virtual com o trabalho "Olá, Pocoyo: a constituição da Atenção Conjunta infantil com o desenho animado", nele o autor afirma que a atenção conjunta está presente no meio virtual quando ele afirma que os "vértices da composição triangular da atenção conjunta aparecem constituídos no cenário virtual da animação." @costa_filho2011[p. 81]. Logo em seguida, ele aprofunda as ideias sobre a ACV e as tecnologias ao desenvolver na sua tese um estudo baseado na Atenção Conjunta envolvida em um aplicativo para tablet e smartphone em forma de jogo tendo como objetivo a observação da Atenção Conjunta na interação da criança em ambiente virtual, representado pelo jogo Mimi©.

Apoiada nos resultados dos trabalhos de Costa Filho, concebemos esta tese cujo objetivo de estudo envolve o processo de Atenção Conjunta Digital (ACD) entre crianças e um livro interativo digital. Não queremos apenas analisar os livros digitais, até porque esse processo já está bastante consolidado, pois há vários estudos sobre o tema @reis_rozados2013 @mello_junior2006 @lebert2008 @lebert2009  @lebert2011 @sehn_fragoso2015.

Nossa hipótese sugere que a atenção conjunta assume uma nova especificidade quando ocorre em um contexto digital. Para isso é preciso verificar quais e de que forma as habilidades da AC assim como da ACV contribuem para a consolidação da Atenção Conjunta Digital.

Para Tomasello (#cite(<tomasello2019>, form: "year")), há nove habilidades que podem ser empregadas de forma individual ou coletiva, são elas: engajamento conjunto, acompanhamento do olhar, acompanhamento do ato de apontar, imitação de atos instrumentais, imitação de atos arbitrários, reação a obstáculos sociais, uso de gestos imperativos e uso de gestos declarativos (incluindo gestos proximais como "mostrar" e gestos distais como "apontar”.

Além dessas habilidades, analisaremos outros dois pontos centrais para a compreensão da AC. O primeiro ponto é a relação entre a AC e a linguística. No início do século XX, Saussure definiu a língua como o objeto da Linguística, através do qual se chegaria às outras manifestações da linguagem. Sendo assim as pesquisas e os trabalhos em Linguística que se relacionam e se justificam entre a língua/linguagem e a Atenção Conjunta são apoiados nos trabalhos de Bruner (#cite(<bruner1975>, form: "year"), #cite(<bruner1983>, form: "year")) e Tomasello (#cite(<tomasello2019>, form: "year")).

Logo, como caracterizar o estatuto da língua e da linguagem na Atenção Conjunta sob a ótica da Linguística? No Capítulo III, demonstraremos que existe um ponto de intersecção entre a Psicologia do Desenvolvimento e a Ciência da Linguagem, no qual o objeto língua/linguagem se constitui através da mediação triádica. Nesse cenário, emerge uma questão central: como se processa a Atenção Conjunta Digital em dispositivos como os livros interativos digitais, nos quais a figura de um sujeito humano — tradicionalmente atento às produções de linguagem da criança — parece ser deslocada ou substituída pela interatividade do suporte? 

Um aspecto adicional que investigaremos é a compreensão dos recursos multimodais mais utilizados pela criança que indicam interatividade com o livro interativo digital. No contexto atual, as crianças em fase de aquisição de linguagem estão frequentemente envoltas nas tecnologias digitais, geralmente de maneira individual ou diádica, isto porque “já nascem imersos na cultura digital” (Alves; Carvalho, 2020, p. 182). No entanto, acreditamos que, se essa interação for promovida de forma triádica, isto é, envolvendo a criança, o livro interativo digital e um mediador virtual, o nível de atenção ao objeto será significativamente ampliado. Consequentemente, esperamos que haja uma facilitação no processo de aquisição de linguagem, uma vez que a Atenção Conjunta (AC) desperta maior foco e empenho naquilo que está sendo desenvolvido.

O presente estudo tem como objetivo central investigar o processo de Atenção Conjunta Digital (ACD) entre crianças em aquisição de linguagem e um livro interativo digital a partir da mediação de um narrador virtual. Para atingir esse objetivo geral, especificamente, procuramos identificar os formatos das cenas de Atenção Conjunta Digital realizados pelas crianças em narrativas interativas digitais; Analisar as pistas multimodais de engajamento das crianças nas cenas de AC Digital; Avaliar como os recursos multimodais presentes na linguagem das crianças podem revelar o engajamento dela quando estão em atenção conjunta com o personagem/narrador virtual; Descrever o estatuto do toque realizado pelas crianças na interação com o livro interativo digital; Investigar de forma qualitativa, as produções linguísticas multimodais resultantes do processo de ACD entre as crianças e o livro interativo digital, observando as singularidades e experiências individuais. Ao cumprir esses objetivos, será possível demonstrar o funcionamento da Atenção Conjunta Digital para a promoção da interatividade e a compreensão leitora em novos objetos de leitura.

Este trabalho está dividido em seis partes: No primeiro capítulo foi traçado um panorama das pesquisas produzidas no Brasil e no mundo com o tema AC, incluindo seu desdobramento em Atenção Conjunta Virtual. Realizamos um estado da arte através de uma revisão bibliográfica das publicações nos últimos 10 anos nas maiores bases de dados nacionais
e internacionais.

O segundo capítulo está dedicado à Teoria da Atenção Conjunta e seus desdobramentos sobre a Atenção Conjunta Virtual e a Atenção Conjunta Digital que pode estar presente nos livros interativos digitais. Ainda neste capítulo há uma pequena explanação a partir de Lévy (#cite(<levy2011>, form: "year")) sobre o que é o virtual e o real, uma vez que tudo que envolve o meio digital está relacionado com o termo virtual que muitas vezes não é compreendido na sua definição plena.

O terceiro capítulo é dedicado à discussão sobre a linguagem e a atenção conjunta, especificamente a linguagem na perspectiva da teoria enunciativa de Émile Benveniste (#cite(<benveniste2005>, form: "year"); (#cite(<benveniste2006>, form: "year"))), uma vez que as pesquisas realizadas neste trabalho mostraram que há uma interlocução entre o processo de triangulação que ocorre na atenção conjunta e sua relação com o aparelho formal da enunciação de Benveniste. Essa relação se funda quando o sujeito se enuncia, ativando o processo da atenção conjunta que, assim como na enunciação, é necessária uma outra pessoa para que a atenção conjunta ou a enunciação se efetive. Nesse capítulo ainda há uma subseção que discute a atenção conjunta e a utilização da linguagem multimodal vinculada à enunciação conforme tratam Fonte; Barros; Cavalcante (#cite(<fonte_cavalcante_barros_2021>, form: "year")).

No quarto capítulo apresentamos a metodologia delineada na investigação da AC Digital, evidenciando a abordagem qualitativa e os objetivos específicos, como a identificação dos formatos de cenas de AC Digital através da análise das pistas multimodais de engajamento. 

No quinto capítulo apresentamos nossas discussões e no sexto as considerações finais. 

Esta tese aborda a importância da Atenção Conjunta (AC), explorando sua evolução ao longo do tempo e sua aplicação no contexto digital, especialmente em livros interativos digitais para crianças. Dentro de três dimensões: científica, social e cultural.

Em relação à importância científica, foi possível perceber que a evolução da AC possibilitou observar a natureza dinâmica e mutável dos estudos científicos voltados para AC, pois ela é um construto teórico que se desenvolveu ao longo do tempo, desde os trabalhos iniciais de Bruner até pesquisas mais recentes sobre AC Digital. Alguns pontos podem ser destacados como a multidisciplinaridade no momento em que a tese enfatiza a interseção entre diferentes áreas do conhecimento, como Psicologia, Linguística, Sociologia e Primatologia, mostrando como a AC é abordada de maneiras diversas.

Dentro da dimensão Social e Cultural o destaque foi a relevância na Aquisição de Linguagem, pois evidenciando o papel da AC no processo de aquisição de linguagem, desde a infância até a vida adulta, e sua aplicação em diversos contextos. Um outro ponto bastante importante foi a incorporação das tecnologias, uma vez que a tese abordou a presença da AC no ambiente digital, reconhecendo que algumas crianças estão imersas nas tecnologias. A interação triádica, especialmente em livros interativos digitais, pode intensificar a atenção e o engajamento na aquisição de linguagem.

Outro aspecto que podemos destacar nesta Tese é a importância Cultural e Educacional na utilização do Livros Interativos Digitais quanto destacamos a importância de investigar a presença da AC em livros digitais interativos, considerando recursos multimodais. Propomos que a utilização dos recursos multimodais pode contribuir para a compreensão da interatividade e promoção da leitura em novos objetos. Pois compreender a AC Digital em crianças pode ter implicações educacionais, informando o design de materiais didáticos e paradidáticos, destacando a importância do engajamento em ambientes virtuais na aquisição de linguagem, o que pode proporcionar uma grande contribuição para a Educação.

Por fim, esta pesquisa destaca a evolução da AC como um construto científico relevante, abrangendo diversas disciplinas e aplicando-se a contextos culturais e educacionais contemporâneos, especialmente no cenário digital. A pesquisa proposta sobre AC Digital em livros interativos digitais pode contribuir significativamente para a compreensão e aprimoramento da interação linguística em ambientes tecnológicos.







